repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=no']
  - repo: https://github.com/pycqa/flake8
    rev: '7.2.0'
    hooks:
    - id: flake8
      additional_dependencies:
        - flake8-bugbear
        - flake8-builtins
        - flake8-comprehensions
        - flake8-docstrings
        - flake8-pytest-style
        - flake8-rst-docstrings
        - pep8-naming

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
        - id: black

  # Should add bandit, lots of work to address all the issues it finds!
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  #   rev: v1.0.5
  #   hooks:
  #     - id: python-bandit-vulnerability-check
  #       args: [--skip, "B101", --recursive, hera_mc]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)

  # Should add darglint, lots of work to address all the issues it finds!
  # - repo: https://github.com/terrencepreilly/darglint
  #   rev: master
  #   hooks:
  #   - id: darglint
