name: hera_mc
channels:
  - conda-forge
dependencies:
  - alembic>=1.8
  - astropy>=5.0.4
  - cartopy>=0.20.0
  - coverage
  - h5py>=3.1.*
  - matplotlib>=3.6.*
  - numpy>=1.19
  - pandas>=1.4.0
  - pip
  - psutil>=5.9.0
  - psycopg>=3.2.2
  - pytest>=6.2.0
  - pytest-cov
  - python-dateutil>=2.8.2
  - pyuvdata>=2.2.9
  - pyyaml>=5.1
  - redis-py>=4.3.4
  - setuptools_scm<7.0|>=7.0.3
  - scipy>=1.3
  - sqlalchemy>=1.4.0
  - tabulate>=0.8.10
  - tornado>=6.2
