name: hera_mc
channels:
  - conda-forge
  - defaults
dependencies:
  - alembic
  - astropy
  - cartopy
  - coverage
  - h5py
  - numpy
  - pandas
  - pip
  - pyqt
  - psutil
  - psycopg2
  - pytest
  - pytest-cov
  - python-dateutil
  - pyuvdata
  - pyyaml
  - redis-py
  - setuptools_scm
  - scipy
  - sqlalchemy
  - tabulate
