"""Include autocorr array

Revision ID: 2d3d5723f499
Revises: a9d4b7805c75
Create Date: 2022-10-04 22:48:23.060289+00:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2d3d5723f499"
down_revision = "a9d4b7805c75"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "antenna_status",
        sa.Column("autocorr", postgresql.ARRAY(sa.Float()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("antenna_status", "autocorr")
    # ### end Alembic commands ###
