"""add rosetta table

Revision ID: 352d10955565
Revises: c4c88519fb71
Create Date: 2020-08-19 14:56:37.359999+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '352d10955565'
down_revision = 'c4c88519fb71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rosetta',
    sa.Column('hpn', sa.String(length=64), nullable=False),
    sa.Column('logical_pn', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('logical_pn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rosetta')
    # ### end Alembic commands ###
