"""add subsystem_error table

Revision ID: 4653b4902dc0
Revises: 93ff199763ac
Create Date: 2017-07-27 19:06:41.684018+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4653b4902dc0"
down_revision = "93ff199763ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subsystem_error",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("time", sa.BigInteger(), nullable=False),
        sa.Column("subsystem", sa.String(length=32), nullable=False),
        sa.Column("mc_time", sa.BigInteger(), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("log", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subsystem_error")
    # ### end Alembic commands ###
