"""added dubitable

Revision ID: 64bc793c6237
Revises: 38aa03a7c923
Create Date: 2017-12-04 04:55:03.111502+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "64bc793c6237"
down_revision = "38aa03a7c923"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dubitable",
        sa.Column("start_gpstime", sa.BigInteger(), nullable=False),
        sa.Column("stop_gpstime", sa.BigInteger(), nullable=True),
        sa.Column("ant_list", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("start_gpstime"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dubitable")
    # ### end Alembic commands ###
