"""made comment part of part_info primary key

Revision ID: 69d2f817e7e7
Revises: 7463268309ab
Create Date: 2020-09-24 22:47:30.199010+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69d2f817e7e7'
down_revision = '7463268309ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
