"""remove histogram_bin_centers

Revision ID: c66b6b222bde
Revises: 5feda4ca9935
Create Date: 2022-01-31 17:24:19.740926+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c66b6b222bde"
down_revision = "d2f22cbd4c5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("antenna_status", "histogram_bin_centers")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "antenna_status",
        sa.Column(
            "histogram_bin_centers", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
