"""added dubitable strings

Revision ID: cadaaf70584f
Revises: d1c54a3474e2
Create Date: 2017-12-03 20:46:53.780908+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadaaf70584f'
down_revision = 'd1c54a3474e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
