"""added dubitable

Revision ID: d1c54a3474e2
Revises: 38aa03a7c923
Create Date: 2017-12-03 18:45:21.939631+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1c54a3474e2'
down_revision = '38aa03a7c923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dubitable',
    sa.Column('start_gpstime', sa.BigInteger(), nullable=False),
    sa.Column('stop_gpstime', sa.BigInteger(), nullable=True),
    sa.Column('ant_list', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.PrimaryKeyConstraint('start_gpstime')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dubitable')
    # ### end Alembic commands ###
