"""changed parts_paper table to parts

Revision ID: e33c1d5684cf
Revises: 3d3c72ecbc0d
Create Date: 2018-01-30 01:02:58.347378+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33c1d5684cf'
down_revision = '3d3c72ecbc0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('hpn', sa.String(length=64), nullable=False),
    sa.Column('hpn_rev', sa.String(length=32), nullable=False),
    sa.Column('hptype', sa.String(length=64), nullable=False),
    sa.Column('manufacturer_number', sa.String(length=64), nullable=True),
    sa.Column('start_gpstime', sa.BigInteger(), nullable=False),
    sa.Column('stop_gpstime', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('hpn', 'hpn_rev')
    )
    op.drop_table('parts_paper')
    op.drop_constraint(u'connections_downstream_part_fkey', 'connections', type_='foreignkey')
    op.drop_constraint(u'connections_upstream_part_fkey', 'connections', type_='foreignkey')
    op.create_foreign_key(None, 'connections', 'parts', ['downstream_part', 'down_part_rev'], ['hpn', 'hpn_rev'])
    op.create_foreign_key(None, 'connections', 'parts', ['upstream_part', 'up_part_rev'], ['hpn', 'hpn_rev'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.create_foreign_key(u'connections_upstream_part_fkey', 'connections', 'parts_paper', ['upstream_part', 'up_part_rev'], ['hpn', 'hpn_rev'])
    op.create_foreign_key(u'connections_downstream_part_fkey', 'connections', 'parts_paper', ['downstream_part', 'down_part_rev'], ['hpn', 'hpn_rev'])
    op.create_table('parts_paper',
    sa.Column('hpn', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('hpn_rev', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('hptype', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('manufacturer_number', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('start_gpstime', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('stop_gpstime', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('hpn', 'hpn_rev', name=u'parts_paper_pkey')
    )
    op.drop_table('parts')
    # ### end Alembic commands ###
