"""Add RTPLaunchRecord table

Revision ID: e679708c5155
Revises: 77c082c87844
Create Date: 2021-03-03 16:18:23.099347+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e679708c5155"
down_revision = "77c082c87844"
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rtp_launch_record",
        sa.Column("obsid", sa.BigInteger(), nullable=False),
        sa.Column("submitted_time", sa.BigInteger(), nullable=True),
        sa.Column("rtp_attempts", sa.BigInteger(), nullable=False),
        sa.Column("jd", sa.BigInteger(), nullable=False),
        sa.Column("obs_tag", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["obsid"],
            ["hera_obs.obsid"],
        ),
        sa.PrimaryKeyConstraint("obsid"),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rtp_launch_record")
    ### end Alembic commands ###
